[package]
name = "schema-type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "schema_type"
path = "src/lib.rs"

[dependencies]
ethers = { version = "2" }
serde = { version = "1" }
